fuel_types = [
    'gas',
    'electric',
    'hybrid',
    'diesel',
]

conditions = [
    'like new',
    'excellent',
    'good',
    'fair',
    'salvage',
]

drive_types = [
    '4wd',
    'fwd',
    'rwd',
]

title_statuses = [
    'clean',
    'rebuilt',
    'salvage',
]

transmissions = [
    'automatic',
    'manual',
]

years = [
    2000,
    2001,
    2002,
    2003,
    2004,
    2005,
    2006,
    2007,
    2008,
    2009,
    2010,
    2011,
    2012,
    2013,
    2014,
    2015,
    2016,
    2017,
    2018,
    2019,
    2020,
    2021,
    2022,
 ]

car_names = [
 'chevrolet acadia',
 'chevrolet altima',
 'chevrolet camaro',
 'chevrolet corvette',
 'chevrolet cruze',
 'chevrolet equinox',
 'chevrolet impala',
 'chevrolet malibu',
 'chevrolet sierra',
 'chevrolet silverado',
 'chevrolet suburban',
 'chevrolet tahoe',
 'chevrolet traverse',
 'chrysler grand caravan',
 'dodge challenger',
 'dodge charger',
 'dodge durango',
 'dodge grand caravan',
 'dodge journey',
 'ford durango',
 'ford edge',
 'ford escape',
 'ford expedition',
 'ford explorer',
 'ford f150',
 'ford f250',
 'ford f350',
 'ford focus',
 'ford fusion',
 'ford mustang',
 'gmc acadia',
 'gmc sierra',
 'gmc terrain',
 'gmc yukon',
 'honda accord',
 'honda civic',
 'honda crv',
 'honda odyssey',
 'honda pilot',
 'hyundai elantra',
 'hyundai santa fe',
 'hyundai sonata',
 'hyundai tucson',
 'jeep cherokee',
 'jeep compass',
 'jeep liberty',
 'jeep patriot',
 'jeep wrangler',
 'kia forte',
 'kia optima',
 'kia sorento',
 'kia soul',
 'mercedes-benz cclass',
 'mercedes-benz eclass',
 'mercedes-benz sclass',
 'nissan altima',
 'nissan frontier',
 'nissan maxima',
 'nissan murano',
 'nissan pathfinder',
 'nissan rogue',
 'nissan sentra',
 'nissan versa',
 'ram 1500',
 'ram 2500',
 'ram 3500',
 'ram sierra',
 'subaru forester',
 'subaru impreza',
 'subaru legacy',
 'subaru outback',
 'toyota 4runner',
 'toyota camry',
 'toyota corolla',
 'toyota highlander',
 'toyota prius',
 'toyota rav4',
 'toyota sienna',
 'toyota tacoma',
 'toyota tundra',
 'volkswagen eclass',
 'volkswagen jetta',
 'volkswagen passat',
 'volkswagen tiguan',
]

models = [ # Used for modeling purposes. Won't be used in production
    # Ford models
    'f150',
    'escape',
    'explorer',
    'f250',
    'mustang',
    'fusion',
    'focus',
    'f350',
    'edge',
    'expedition',
    # Chevrolet models
    'silverado',
    'equinox',
    'malibu',
    'tahoe',
    'corvette',
    'impala',
    'cruze',
    'camaro',
    'suburban',
    'traverse',
    # Toyota models
    'camry',
    'tacoma',
    'corolla',
    'rav4',
    'prius',
    'tundra',
    '4runner',
    'sienna',
    'highlander',
    # Honda models
    'accord',
    'civic',
    'crv',
    'odyssey',
    'pilot',
    # Nissan models
    'altima',
    'rogue',
    'sentra',
    'maxima',
    'pathfinder',
    'versa',
    'murano',
    'frontier',
    # Jeep models
    'wrangler',
    'grand cherokee', # Important this is before cherokee for matching
    'cherokee',
    'liberty',
    'patriot',
    'compass',
    # Ram models
    '1500',
    '2500',
    '3500',
    # GMC models
    'sierra',
    'acadia',
    'yukon',
    'terrain',
    # Note: Left BMW off since naming conditions are too varied
    # Dodge models
    'charger',
    'grand caravan',
    'challenger',
    'durango',
    'journey',
    # Mercedes-Benz models
    'cclass',
    'eclass',
    'sclass',
    # Hyundai models
    'sonata',
    'elantra',
    'santa fe',
    'tucson',
    # Subaru models
    'outback',
    'forester',
    'impreza',
    'legacy',
    # Volkswagen models
    'jetta',
    'passat',
    'tiguan',
    # Kia models
    'soul',
    'optima',
    'sorento',
    'forte', 
]

